# Generated by Django 5.1.2 on 2024-10-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/', verbose_name='Thumbnail')),
                ('slug', models.SlugField(unique=True)),
                ('published_at', models.DateTimeField(editable=False, null=True, verbose_name='Published At')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('num_likes', models.IntegerField(default=0, editable=False, verbose_name='Likes')),
                ('num_views', models.IntegerField(default=0, editable=False, verbose_name='Views')),
                ('tags', models.ManyToManyField(related_name='videos', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=255, verbose_name='Video')),
                ('status', models.CharField(choices=[('UPLOADED_STARTED', 'Uploaded Started'), ('PROCESSING_STARTED', 'Process Started'), ('PROCESSING_FINISHED', 'Process Finished'), ('PROCESSING_ERROR', 'Process Error')], default='UPLOADED_STARTED', max_length=20, verbose_name='Status')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='video_media', to='core.video', verbose_name='Video')),
            ],
        ),
    ]
