# Generated by Django 5.1.2 on 2024-10-22 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Vídeo', 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='video',
            name='num_views',
            field=models.IntegerField(default=0, editable=False, verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='status',
            field=models.CharField(choices=[('UPLOADED_STARTED', 'Upload Iniciado'), ('PROCESSING_STARTED', 'Processamento Iniciado'), ('PROCESSING_FINISHED', 'Processamento Finalizado'), ('PROCESSING_ERROR', 'Erro no Processamento')], default='UPLOADED_STARTED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='video_media', to='core.video', verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='video_path',
            field=models.CharField(max_length=255, verbose_name='Vídeo'),
        ),
    ]
